from enum import Enum


class RuntimeStage(str, Enum):
    BOOT = "BOOT"
    CONFIG_LOADED = "CONFIG_LOADED"
    API_CHECKED = "API_CHECKED"
    INSTRUMENTS_SYNCED = "INSTRUMENTS_SYNCED"
    ACCOUNT_RECONCILED = "ACCOUNT_RECONCILED"
    MARKET_READY = "MARKET_READY"
    MODELS_READY = "MODELS_READY"
    READY = "READY"
    RUNNING = "RUNNING"
    DEGRADED = "DEGRADED"
    SAFE_MODE = "SAFE_MODE"
    STOPPED = "STOPPED"


class OrderState(str, Enum):
    INTENT_CREATED = "INTENT_CREATED"
    PRECHECK_PASSED = "PRECHECK_PASSED"
    SUBMITTING = "SUBMITTING"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    LIVE = "LIVE"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"
    UNKNOWN_RECONCILING = "UNKNOWN_RECONCILING"


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


class ProductType(str, Enum):
    SPOT = "SPOT"
    SPOT_MARGIN = "SPOT_MARGIN"
    DERIVATIVE = "DERIVATIVE"
